# config.yml

GUUE_DIR: guue # directory with PDFs
DATA_DIR: data # directory with data (previously parsed by opendata)
BID_OPENING_MARKER_START: Modalità di apertura delle offerte
BID_OPENING_MARKER_END: "Sezione VI: Altre informazioni"
FILE_BID_TEXT: bid_opening_text.csv # file created after PDF parsing (input for LLM)
FILE_BID_TEXT_DATE_LABEL: bid_opening_text_date_label.csv # annotated dates to be compared with FILE_BID_TEXT_DATE
FILE_BID_TEXT_DATE: bid_opening_text_date.csv # file after CSV parsing to find dates with LLM
CSV_SEP: ;
TED_URL: https://ted.europa.eu/TED # Text of a URL to be ignored when reading PDFs
OPENAI_MODEL_NAME: gpt-3.5-turbo # [gpt-4, gpt-4-32k]
TIME_SLEEP: 3 # seconds
BID_SAMPLE_SIZE: 10 # Sets a sample size (to be used instead of the total size of the dataset); 0 means to use the whole dataset instead of a sample