# config.yml

DOWNLOAD_DIR: /Volumes/SAMSUNG-PHD/PhD/Corsi da seguire/Knowledge management and information extraction from structured and unstructured data for process mining (techniques, algorithms, and tools)/Python - GUUE in CSV per LOG # Directory where the files were downloaded
GUUE_DIR: guue # directory with PDFs
DATA_DIR: data # directory with data (extracted parsing the PDFs)
BID_OPENING_MARKER_START: Modalità di apertura delle offerte
BID_OPENING_MARKER_END: "Sezione VI: Altre informazioni"
FILE_BID_TEXT: bid_opening_text_LANG.csv # file created after PDF parsing with text (input for LLM); replace LANG with language code
FILE_BID_TEXT_DATE_LABEL: bid_opening_text_date_LANG_label.csv # annotated dates to be compared with FILE_BID_TEXT_DATE; replace LANG with language code
FILE_BID_TEXT_DATE: bid_opening_text_date_LANG.csv # file after CSV parsing to find dates with LLM; replace LANG with language code
CSV_SEP: ;
TED_URL: https://ted.europa.eu/TED # Text of a URL to be ignored when reading PDFs
OPENAI_MODEL_NAME: gtp-4o # [gpt-4, gtp-4o, gpt-4-32k, gpt-3.5-turbo]
TIME_SLEEP: 3 # seconds
BID_SAMPLE_SIZE: 10 # Sets a sample size (to be used instead of the total size of the dataset); 0 means to use the whole dataset instead of a sample
YEAR_START: 2016 # Starting year (included)
YEAR_END: 2022 # End year (included)
LOG_PDF_EXTRACTION: ted_log_pdf_extraction.csv # Timing to extract texts markes from PDFs
LOG_PDF_EXTRACTION_HEADER: lang;time_start;time_end;time_delta;num_files
LOG_PDF_LLM: ted_log_pdf_llm.csv # Timing to extract dates from PDFs with LLM
LOG_PDF_LLM_HEADER: lang;model;time_start;time_end;time_delta